services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: plugb_sample_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped