# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: read

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    # pack baut selbst -> kein separater build-Step nötig
    - name: Pack PlugB
      run: dotnet pack src/PlugB/PlugB.csproj --configuration Release --output ${{ env.NuGetDirectory }} -p:GeneratePackageOnBuild=false -m:1

    - name: Upload NuGet packages artifact
      uses: actions/upload-artifact@v6
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: |
          ${{ env.NuGetDirectory }}/*.nupkg
          ${{ env.NuGetDirectory }}/*.snupkg

  run_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          10.0.x

    - name: Build
      run: dotnet build --configuration Release -m:1 -p:GeneratePackageOnBuild=false

    - name: Test (unit)
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal -m:1 --filter "Category!=Integration"

    - name: Test (integration)
      if: runner.os == 'Linux'
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal -m:1 --filter "Category=Integration"

  deploy:
    runs-on: windows-latest
    needs: [ create_nuget, run_test ]
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --skip-duplicate --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
          }